### ISSUE TITLE
Create new PyPI release after latest merge

### ISSUE THREAD

**Issue by schakalakka** [randyzwitch/streamlit-letsplot#10]
Could you create a new release which includes the ggsize fix?

**Comment by randyzwitch** [comment]
Yeah, I'll try to get that up today.

Just an FYI, I'm no longer at Streamlit, so if you'd like to be the maintainer of this project I can add you as a collaborator. Otherwise, updates are unlikely from me unless I go back to writing software again.

**Comment by randyzwitch** [comment]
Okay, you're all set. 0.0.3 is on PyPI. I also set up a GitHub Action to automate this, so if changes are committed in the future and a new tag is created it will automatically get uploaded to PyPI.

**Comment by schakalakka** [comment]
Thank you @randyzwitch! 
I am not sure how much time I have in the future but I think it cannot hurt to add me as a collaborator. 

Slightly off topic: Do you know why streamlit-letsplot is not implemented into streamlit directly?
