### ISSUE TITLE
generateStaticHtmlPage() Exception

### ISSUE THREAD

**Issue by schakalakka** [randyzwitch/streamlit-letsplot#8]
Already mentioned in issue #7.  

I am still getting the following error when using st_letsplot:
generateStaticHtmlPage() - Exception: Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread

Is there a workaround? Are there several methods gnerating the html page? Or is it a bug in streamlit or lets-plot?

**Comment by randyzwitch** [comment]
Unfortunately, it's not clear to me how Let's Plot is working...all I should be doing is using their HTML representation method, but somehow it's running multi-threaded (perhaps due to the Kotlin underpinnings?). I'm open to suggestions if anyone out there knows what the problem might be 🤷

**Comment by schakalakka** [comment]
I [forwarded it](https://github.com/JetBrains/lets-plot/issues/595) to the lets-plot folks and it seems that it will be resolved in a future release.

**Comment by randyzwitch** [comment]
Great, sounds like it's something low-level as I expected

**Comment by schakalakka** [comment]
The issue seems to be resolved by the lets-plot folks.
